name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.rokkon.com/io-pipeline/gitea-runner:latest
      options: --network host

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker is available
        run: |
          docker --version
          docker ps

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        env:
          GITEA_USER: ${{ secrets.GIT_USER }}
          GITEA_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: ./gradlew clean build test --no-daemon --info --configuration-cache

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/test-results/
            build/reports/tests/

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/

      - name: Publish to Gitea Maven
        if: gitea.ref == 'refs/heads/main'
        env:
          GITEA_USER: ${{ secrets.GIT_USER }}
          GITEA_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: ./gradlew publishAllPublicationsToGiteaRepository --no-daemon

      - name: Publish to GitHub Packages
        if: gitea.ref == 'refs/heads/main'
        env:
          GH_USER: ${{ gitea.actor }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository --no-daemon

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: gitea.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.rokkon.com
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image with Quarkus
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.GIT_USER }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GIT_TOKEN }}
        run: |
          ./gradlew build \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.additional-tags=${{ gitea.sha }} \
            --no-daemon